stages:
  - publish
  - deploy

variables:
  IMAGE: $CI_REGISTRY/vh/vh-front:$CI_COMMIT_SHORT_SHA

publish:
  image: docker:latest
  stage: publish
  tags:
    - dockerbuild
  services:
    - docker:19.03.12-dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/vh/vh-front:$CI_COMMIT_SHORT_SHA .
    - docker push $IMAGE

deploy:
  image: docker:latest
  stage: deploy
  tags:
    - dockerbuild
  script:
    #- docker -H $HOST login  -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker -H $HOST pull $IMAGE
    - docker -H $HOST rm -f vh-front
    - docker -H $HOST run -d --net=vh --name vh-bbpayment --restart always -p 80:80 $IMAGE
  environment:
    name: development
    url: http://51.15.238.1
  only:
    - development
