services:
  vh-front:
    image: "${IMAGE_NAME}"
    restart: unless-stopped
    cpus: '0.1'
    mem_limit: 50M
    ports:
      - 8081:80
    volumes:
      - /opt/vh/vh-front/public/config/:/usr/share/nginx/html/config/
networks:
  default:
    name: vh
    external: true
