backend:
  name: test-repo
  branch: master
  repo: vh/vh-docs
  auth_type: pkce
  app_id: 06d8931eddc3c8f54f5a8c7920eac876e5bcc517300c5286aa62ce69a760b570
  api_root: https://gitlab.bbdev.team/api/v4
  base_url: https://gitlab.bbdev.team
  auth_endpoint: oauth/authorize
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
  - format: "json"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.json"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Publish Date", name: "date", widget: "datetime" }
        - { label: "Body", name: "body", widget: "markdown"}
        - label: 'Cats'
          name: "cats"
          widget: list
          fields:
            - { label: "Name", name: "name", widget: "string"}
            - { label: "Description", name: "description", widget: "text"}